### ISSUE TITLE
Angular 2 won't compile in webpack when using built SDK

### ISSUE THREAD

**Issue by JoshElias** [jonathan-casarrubias/loopback-sdk-builder#42]
I've followed the instructions for generating the angular2 sdk in the documention and receive the following error when building my project with webpack.

```
ERROR in ./src/client/app/shared/lb-services/services/api.d.ts
Module build failed: Error: Debug Failure. False expression: Output generation failed
    at Object.assert (C:\Users\Josh\Documents\Github\muskoka\node_modules\typescript\lib\typescript.js:2099:23)
    at Object.transpileModule (C:\Users\Josh\Documents\Github\muskoka\node_modules\typescript\lib\typescript.js:53173:18)
    at State.fastEmit (C:\Users\Josh\Documents\Github\muskoka\node_modules\awesome-typescript-loader\dist.babel\host.js:302:43)
    at transform (C:\Users\Josh\Documents\Github\muskoka\node_modules\awesome-typescript-loader\dist.babel\index.js:215:53)
    at _callee3$ (C:\Users\Josh\Documents\Github\muskoka\node_modules\awesome-typescript-loader\dist.babel\index.js:265:42)
    at tryCatch (C:\Users\Josh\Documents\Github\muskoka\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Josh\Documents\Github\muskoka\node_modules\regenerator-runtime\runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Josh\Documents\Github\muskoka\node_modules\regenerator-runtime\runtime.js:95:21)
    at fulfilled (C:\Users\Josh\Documents\Github\muskoka\node_modules\awesome-typescript-loader\dist.babel\index.js:31:32)
    at run (C:\Users\Josh\Documents\Github\muskoka\node_modules\core-js\modules\es6.promise.js:89:22)
    at C:\Users\Josh\Documents\Github\muskoka\node_modules\core-js\modules\es6.promise.js:102:28
    at flush (C:\Users\Josh\Documents\Github\muskoka\node_modules\core-js\modules\_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
 @ ./src/client/app/shared/lb-services/index.ts 22:9-36
```

**Comment by jonathan-casarrubias** [comment]
Ok I see, as work around in tsconfig set es6 instead of es5. I will change object.assign for other es5 funcion to allow backwards compatibility

**Comment by JoshElias** [comment]
Yeah I'm using this as a starter: https://github.com/AngularClass/angular2-webpack-starter. It just seems to be that one `api.d.ts` file that's giving me the problem. I wonder if its my tsconfig settings? I tried rolling back to typescript 1.8  from 2.0 and that didn't work. Thanks for the speedy response!

**Comment by jonathan-casarrubias** [comment]
landed in release candidate 2
